import pandas as pd
import os

# Ez egy kiterjesztett lista diverz FDA gyógyszerekből, hogy ne függjünk a szervertől
diverse_drugs = [
    {"Name": "Revefenacin", "SMILES": "CN1CCC(CC1)N(C)C(=O)C2=C(C=CC=C2)NC(=O)NC3=CC=C(C=C3)C4=CC=CC=C4C(=O)NO"},
    {"Name": "Lapatinib", "SMILES": "CS(=O)(=O)CCNCC1=CC=C(O1)C2=CC3=C(C=C2)N=CN=C3NC4=CC(C(=C4)OCC5=CC(=CC=C5)F)Cl"},
    {"Name": "Afatinib", "SMILES": "CN(C)C/C=C/C(=O)NC1=C(C=C2C(=C1)N=CN=C2NC3=CC(C(=C4)Cl)F)O[C@H]4CCOC4"},
    {"Name": "Nilotinib", "SMILES": "Cc1ccc(cc1Nc2nccc(n2)c3cccnc3)NC(=O)c4ccc(cc4C(F)(F)F)n5cc(cn5)C"},
    {"Name": "Pazopanib", "SMILES": "Cc1ccc(cc1N(C)c2nc(nc3c2cnn3C)Nc4ccc(cc4)S(=O)(=O)N)C"},
    {"Name": "Sunitinib", "SMILES": "CCN(CC)CCNC(=O)c1c(C)[nH]c(c1C)/C=C2\c3cc(F)ccc3NC2=O"},
    {"Name": "Regorafenib", "SMILES": "CNC(=O)c1ccc(cc1F)Oc2cc(nc(c2)Cl)Nc3ccc(cc3Cl)C(F)(F)F"},
    {"Name": "Axitinib", "SMILES": "CNC(=O)c1ccccc1Sc2ccc3c(c2)c(cn3)/C=C/c4ccccn4"},
    {"Name": "Dasatinib", "SMILES": "Cc1cccc(c1Cl)NC(=O)c2cnc(s2)Nc3cc(nc(n3)C)N4CCN(CC)CC4"},
    {"Name": "Bosutinib", "SMILES": "CN1CCN(CC1)CCCOc2c(OC)cc3c(Nc4cc(Cl)c(Cl)cc4C#N)ncncc32"},
    {"Name": "Ponatinib", "SMILES": "CN1CCN(CC1)cc2ccc(cc2)C(=O)Nc3ccc(C)c(c3)C#Cc4cnc5n4nccc5"},
    {"Name": "Cabozantinib", "SMILES": "COc1cc2c(cc1OC)nc(cc2Oc3ccc(cc3F)NC(=O)C4(CC4)C(=O)Nc5ccc(cc5)F)Cl"},
    {"Name": "Lenvatinib", "SMILES": "CNC(=O)Nc1ccc(cc1Cl)Oc2cc(nc3cc(OC)c(OC)cc23)C(=O)N"},
    {"Name": "Vandetanib", "SMILES": "CN1CCC(CC1)COc2c(OC)cc3c(Nc4ccc(Br)cc4F)ncncc32"},
    {"Name": "Tofacitinib", "SMILES": "C[C@@H]1CCN(C[C@@H]1N(C)c2c3cc[nH]c3ncn2)C(=O)CC#N"},
    {"Name": "Ruxolitinib", "SMILES": "C1CCC(C1)[C@@H](CC#N)n2cc(cn2)c3c4cc[nH]c4ncn3"},
    {"Name": "Baricitinib", "SMILES": "CCS(=O)(=O)N1CC(C1)(CC#N)n2cc(cn2)c3c4cc[nH]c4ncn3"},
    {"Name": "Upadacitinib", "SMILES": "CC[C@@H]1CN(C1)c2c3cc[nH]c3ncn2"},
    {"Name": "Selumetinib", "SMILES": "CN1C=C(C=N1)C(=O)Nc2ccc(F)c(c2Cl)Nc3ccc(cc3I)F"},
    {"Name": "Trametinib", "SMILES": "CN1C(=O)N(C2=CC(=C(C=C2C1=O)NC3=C(C=C(C=C3)I)F)F)C4=C(C=CC=C4Cl)F"},
    {"Name": "Cobimetinib", "SMILES": "C1CC(NC1)CN2CCC(C(C2)F)(C3=C(C=C(C=C3)I)F)O"},
    {"Name": "Binimetinib", "SMILES": "CNC1=C(C=C(C=C1)I)Nc2c(F)cc(n2C)C(=O)NO"},
    {"Name": "Encorafenib", "SMILES": "COCC(=O)NC1=C(C=C(C=C1)Cl)C(=O)C2=CN(C=N2)C3=C(C=C(C=C3)F)F"},
    {"Name": "Dabrafenib", "SMILES": "CC(C)(C)c1nc(c(s1)-c2cccc(NS(=O)(=O)c3c(F)cccc3F)c2F)c4nccn4"},
    {"Name": "Ibrutinib", "SMILES": "C=CC(=O)N1CCC[C@@H]1c2n(nc3c2ccc(cc3)Oc4ccccc4)C"},
    {"Name": "Acalabrutinib", "SMILES": "CC#CC(=O)N1CCC[C@H]1c2nc(c3n2cccc3)C(=O)N"},
    {"Name": "Zanubrutinib", "SMILES": "C=CC(=O)N1CCC[C@H]1c2nc3c(n2)c(c(cn3)Oc4ccccc4)N"},
    {"Name": "Idelalisib", "SMILES": "CCC1=NC(=C2C(=N1)N=CN=C2N)C3=CC=CC=C3C4=C5C=CC=CC5=NC=C4"},
    {"Name": "Duvelisib", "SMILES": "CCC1=NC(=C2C(=N1)N=CN=C2N)C3=CC=CC=C3Cl"},
    {"Name": "Copanlisib", "SMILES": "COc1cc(OC)c(c(OC)c1)C2=NC(=NC=N2)N3CCN(CC3)C(=O)C4=CC=CN=C4"},
    {"Name": "Alpelisib", "SMILES": "CC(C)(C)NC(=O)Nc1nc(cs1)c2ccnc(n2)N3CCC(C3)C(=O)N"},
    {"Name": "Ribociclib", "SMILES": "CN(C)C(=O)c1cc2c(nc(nc2n1C3CCCC3)Nc4ccc(cc4)CN5CCN(CC5)C)N"},
    {"Name": "Palbociclib", "SMILES": "CC(=O)c1c(C)c2cc(Nc3ccc(nc3)N4CCNCC4)nc(N)c2n(C5CCCC5)c1=O"},
    {"Name": "Abemaciclib", "SMILES": "CCN1CCN(CC1)Cc2ccc(cc2)Nc3ncc(c(n3)c4cc5c(cc4F)n(c5)C(C)C)F"},
    {"Name": "Everolimus", "SMILES": "C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[C@H](C(=O)[C@@H]([C@@H](/C(=C/[C@H](C(=O)C[C@H](OC(=O)[C@@H]3CCCCN3C(=O)C(=O)[C@@]2(O1)O)[C@H](C)C[C@@H]4CC[C@H]([C@@H](C4)OC)OCCOC)C)/C)O)C)C)OC)/C)[C@H](C)OC"},
    {"Name": "Sirolimus", "SMILES": "C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[C@H](C(=O)[C@@H]([C@@H](/C(=C/[C@H](C(=O)C[C@H](OC(=O)[C@@H]3CCCCN3C(=O)C(=O)[C@@]2(O1)O)[C@H](C)C[C@@H]4CC[C@H]([C@@H](C4)OC)O)C)/C)O)C)C)OC)/C)[C@H](C)OC"},
    {"Name": "Temsirolimus", "SMILES": "CC1(CO[C@@H](O1)C[C@@H]2C[C@H]([C@@H]([C@H](C2)OC)O[C@@H]3C[C@H](OC(=O)[C@@H]4CCCCN4C(=O)C(=O)[C@]5(O[C@H]6CC[C@@H](C[C@@H]6/C(=C/C=C/C=C/[C@H](C[C@H](C(=O)[C@@H]([C@@H](/C(=C/[C@H](C(=O)C)C)/C)O)C)C)OC)/C)[C@H]5C)O)C)C)C"},
    {"Name": "Venetoclax", "SMILES": "CC1(CCC(=C(C1)c2ccc(cc2)Cl)CN3CCN(CC3)c4cc(c(cc4C(=O)NS(=O)(=O)c5ccc(cc5)NCC6CCOCC6)S(=O)(=O)C(F)(F)F)Oc7ccc8c(c7)ccn8C)C"},
    {"Name": "Olaparib", "SMILES": "C1CC1C(=O)N2CCN(CC2)C(=O)c3c(cc(cc3F)Cc4[nH]nc5c4cccc5)O"},
    {"Name": "Niraparib", "SMILES": "c1ccc(cc1)[C@H]2CNCC[C@H]2c3ccc(cc3)n4c[nH]c5c4cccc5"},
    {"Name": "Rucaparib", "SMILES": "CNCc1ccc(cc1)c2c3cc[nH]c3nc4c2cc(F)cc4NCC"},
    {"Name": "Talazoparib", "SMILES": "C[C@]1(n2c(nnc2-c3ccc(F)cc3)C4=C1c5cc(F)cc(c5NC4=O)N6CCNCC6)C"},
    {"Name": "Veliparib", "SMILES": "C[C@@]1(CCCN1)c2cc3[nH]cnc3cc2C(=O)N"},
    {"Name": "Bortezomib", "SMILES": "CC(C)C[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)c2nccnc2)B(O)O"},
    {"Name": "Carfilzomib", "SMILES": "CC(C)C[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](Cc3ccccc3)NC(=O)CO)C(=O)[C@@H]4OC4(C)C"},
    {"Name": "Ixazomib", "SMILES": "CC(C)C[C@H](NC(=O)Cc1cc(Cl)ccc1Cl)B(O)O"},
    {"Name": "Darolutamide", "SMILES": "CC(C)N1C(=O)N(C2=C1C=C(C=C2)C#N)C3=C(C=CC(=C3)C(F)(F)F)C(C)O"},
    {"Name": "Enzalutamide", "SMILES": "CC1(C(=O)N(C(=S)N1c2ccc(cc2F)C#N)c3ccc(cc3)C(=O)NC)C"},
    {"Name": "Apalutamide", "SMILES": "CC1(C(=O)N(C(=S)N1c2ccc(cc2F)C#N)c3ccc(cc3)C(=O)N(C)C)C"},
    {"Name": "Abiraterone", "SMILES": "CC12CCC(O)CC1=CCC3C2CCC4(C)C3CCC4=Cc5cccnc5"},
    {"Name": "Bicalutamide", "SMILES": "CC(O)(Cc1ccc(cc1)S(=O)(=O)c2ccc(cc2)F)C(=O)Nc3ccc(cc3C(F)(F)F)C#N"},
]

df = pd.DataFrame(diverse_drugs)
df.to_csv("full_fda_library.csv", index=False)
print(f"Siker! Létrehozva: full_fda_library.csv ({len(df)} diverz molekula).")
