@echo off
mkdir docking_results
echo [Progress] Docking CABAZITAXEL (1/4)...
vina_1.2.7_win.exe --config config.txt --ligand ligands/CABAZITAXEL.pdbqt --out docking_results/CABAZITAXEL_out.pdbqt > docking_results/CABAZITAXEL_log.txt 2>&1
echo [Progress] Docking DOCETAXEL (2/4)...
vina_1.2.7_win.exe --config config.txt --ligand ligands/DOCETAXEL.pdbqt --out docking_results/DOCETAXEL_out.pdbqt > docking_results/DOCETAXEL_log.txt 2>&1
echo [Progress] Docking DOCETAXEL_ANHYDROUS (3/4)...
vina_1.2.7_win.exe --config config.txt --ligand ligands/DOCETAXEL_ANHYDROUS.pdbqt --out docking_results/DOCETAXEL_ANHYDROUS_out.pdbqt > docking_results/DOCETAXEL_ANHYDROUS_log.txt 2>&1
echo [Progress] Docking PACLITAXEL (4/4)...
vina_1.2.7_win.exe --config config.txt --ligand ligands/PACLITAXEL.pdbqt --out docking_results/PACLITAXEL_out.pdbqt > docking_results/PACLITAXEL_log.txt 2>&1
echo [Progress] All docking tasks completed.
